#EasyMail配置文件
#Design By MossCG

#前言
#当你确认配置没问题后，请将以下选项修改为true后再启动喵
enable: true

#----------------------------------
#Http请求模块信息

#请求密钥
token: "1234567890"
#Http服务器端口
httpPort: 7654

#----------------------------------
#邮箱模块信息

#发送邮箱账号信息
mailAccount: ""
mailPassword: ""
mailSMTPHost: ""
#接受邮箱账号信息
mailReceive: ""

#----------------------------------
#是否显示调试信息
debug: true
